version: 2
updates:
- package-ecosystem: npm
  directory: "/front"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.6
    - 3.6.7
    - 3.6.8
  - dependency-name: karma
    versions:
    - 6.0.4
    - 6.1.2
    - 6.2.0
    - 6.3.0
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
- package-ecosystem: pip
  directory: "/backend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: flask-sqlalchemy
    versions:
    - 2.4.4
